[supervisord]
nodaemon=true

[program:deploy_hubserving]
command=/bin/bash -c "cd /paddle/PaddleOCR && export CUDA_VISIBLE_DEVICES=0 && ./deploy_hubserving.sh"
autostart=true
autorestart=true

[program:flask_service_mrz]
command=/bin/bash -c "cd /yolov5 && python3 server_mrz.py"
autostart=true
autorestart=true

[program:flask_service_type_code_sex]
command=/bin/bash -c "cd /yolov5 && python3 server_type_code_sex.py"
autostart=true
autorestart=true